% Thomas Satterly
% AAE 537
% Homework 4, Part (iii)

close all;
clc;
clear;

% Setup standard parameters
aae537.hw4.setup();


CPR = 20;
beta = 0;
M5_c = 0.4;

% Run engine solver
[engineData, error] = aae537.hw4.solveEngine(...
    'eta_c', eta_c, ...
    'eta_b', eta_b, ...
    'eta_t', eta_t, ...
    'eta_n', eta_n, ...
    'h', h, ...
    'Tt4', Tt4_max, ...
    'M0', 1, ...
    'q', q, ...
    'T0', T0, ...
    'CPR', CPR, ...
    'gamma', gamma, ....
    'cp', cp, ...
    'm_dot', m_dot, ...
    'beta', beta, ...
    'R', R, ...
    'M5_c', M5_c);

fprintf('Thrust: %0.3f lbf\nSFC: %0.4f lbm/(lbf*hr)\nTurbine Area: %0.3f ft^2\n', engineData.thrust, engineData.SFC * 3600, engineData.A5_c);







