% Thomas Satterly
% AAE 537
% Homework 4, Part (iv)

close all;
clc;
clear;

% Setup standard parameters
aae537.hw4.setup();



beta = 0.5;
M5_b = 0.5;
A5_c = 15.645512875129334; % ft^2
M0 = 4;
CPRs = linspace(0.1, 2, 100);
for i = 1:numel(CPRs)
    CPR = CPRs(i);
    % Run engine solver
    [~, error(i)] = aae537.hw4.solveEngine(...
        'eta_c', eta_c, ...
        'eta_b', eta_b, ...
        'eta_t', eta_t, ...
        'eta_ab', eta_ab, ...
        'eta_n', eta_n, ...
        'h', h, ...
        'Tt4', Tt4_max, ...
        'Tt7', Tt7_max, ...
        'M0', M0, ...
        'q', q, ...
        'T0', T0, ...
        'CPR', CPR, ...
        'gamma', gamma, ....
        'cp', cp, ...
        'm_dot', m_dot, ...
        'beta', beta, ...
        'R', R, ...
        'M5_b', M5_b, ...
        'A5_c', A5_c);
    
end

% Find where the error is at a minimum
[~, index] = min(abs(error));
CPR = CPRs(index);

% Run once more at this condition to get engine data
[engineData, ~] = aae537.hw4.solveEngine(...
        'eta_c', eta_c, ...
        'eta_b', eta_b, ...
        'eta_t', eta_t, ...
        'eta_ab', eta_ab, ...
        'eta_n', eta_n, ...
        'h', h, ...
        'Tt4', Tt4_max, ...
        'Tt7', Tt7_max, ...
        'M0', 1, ...
        'q', q, ...
        'T0', T0, ...
        'CPR', CPR, ...
        'gamma', gamma, ....
        'cp', cp, ...
        'm_dot', m_dot, ...
        'beta', beta, ...
        'R', R, ...
        'M5_b', M5_b, ...
        'A5_c', A5_c);
    
fprintf('Thrust: %0.3f lbf\nSFC: %0.4f lbm/(lbf*hr)\nCPR: %0.3f\n', engineData.thrust, engineData.SFC * 3600, CPR);







